[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
curs_7 = "CxL91vmcDCWVFY84BvY1TaU8hwoRutgzCgrjGEQ3hhYm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
